services:
  redis:
    image: redis:8.0.1
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--loglevel", "warning", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes: 
      - redis-data-volume:/data
    networks:
      - core-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis-data-volume:
    name: redis-data-volume

networks:
  core-network:
    external: true
