services:
  beta-quiz-service:
    image: emils-nuc-server:5000/quiz-service:7d9f79de4
    container_name: beta-quiz-service
    restart: unless-stopped
    env_file:
      - stacks.env
      - stacks.beta.env
    volumes:
      - beta-quiz-service-uploads-volume:/uploads
    networks:
      - core-network
volumes:
  beta-quiz-service-uploads-volume:
    name: beta-quiz-service-uploads-volume
networks:
  core-network:
    external: true
