services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Private Docker Registry"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/emils-nuc-server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/emils-nuc-server.key
    volumes:
      - registry-auth-volume:/auth
      - registry-certs-volume:/certs
      - registry-data-volume:/var/lib/registry
    networks:
      - core-network

  registry-browser:
    image: klausmeyer/docker-registry-browser:1.9.1
    container_name: registry-browser
    hostname: registry-browser
    restart: unless-stopped
    ports:
      - "15713:80"
    env_file: ./stack.env
    environment:
      ADDRESS: 0.0.0.0
      PORT: 80
      DOCKER_REGISTRY_URL: https://registry:5000
      NO_SSL_VERIFICATION: "true"
      CA_FILE: /certs/emils-nuc-server.crt
      TZ: Europe/Stockholm
      ENABLE_DELETE_IMAGES: "true"
    depends_on:
      - registry
    networks:
      - core-network
    volumes:
      - registry-certs-volume:/certs:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -T 5 -qO- http://127.0.0.1 >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  registry-auth-volume:
    name: registry-auth-volume
  registry-certs-volume:
    name: registry-certs-volume
  registry-data-volume:
    name: registry-data-volume

networks:
  core-network:
    external: true
