services:
  beta-quiz:
    image: emils-nuc-server:5000/quiz:8837809f7
    container_name: beta-quiz
    restart: unless-stopped
    env_file:
      - stacks.env
      - stacks.beta.env
    networks:
      - core-network
networks:
  core-network:
    external: true
