services:
  beta-quiz:
    image: emils-nuc-server:5000/quiz:3479a52bf
    container_name: beta-quiz
    restart: unless-stopped
    env_file:
      - stacks.env
      - stacks.beta.env
    networks:
      - core-network
    healthcheck:
      test: ["CMD-SHELL", "wget -T 5 -qO- http://127.0.0.1 >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
networks:
  core-network:
    external: true
