services:
  beta-klurigo-service:
    image: emils-nuc-server:5000/klurigo-service:eae67af
    container_name: beta-klurigo-service
    restart: unless-stopped
    env_file:
      - stacks.env
      - stacks.beta.env
    volumes:
      - beta-klurigo-service-uploads-volume:/uploads
    networks:
      - core-network
    healthcheck:
      test: ["CMD-SHELL", "wget -T 5 -qO- http://127.0.0.1:8080/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
volumes:
  beta-klurigo-service-uploads-volume:
    name: beta-klurigo-service-uploads-volume
networks:
  core-network:
    external: true
