services:
  memos:
    image: neosmemo/memos:0.25.3
    container_name: memos
    restart: unless-stopped
    ports:
      - "15330:80"
    env_file: ./stack.env
    volumes:
      - memos-volume:/var/opt/memos
    networks:
      - core-network
    healthcheck:
      test: ["CMD-SHELL", "wget -T 5 -qO- http://127.0.0.1 >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  memos-volume:
    name: memos-volume

networks:
  core-network:
    external: true
